backend:
  name: git-gateway
  branch: main # Branch to update

publish_mode: editorial_workflow


# These lines should *not* be indented
media_folder: "public/content/media" # Media files will be stored in the repo under public/content/media
public_folder: "public/content/media" # The src attribute for uploaded media will begin with /media

collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog post" # Used in the UI
    folder: "public/content/blog" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "publish", widget: "datetime"}
      - {label: "Body", name: "body", widget: "markdown"}
