backend:
  name: git-gateway
  branch: main # Branch to update

publish_mode: editorial_workflow

media_folder: "media" # Media files will be stored in the repo under media

# These lines should *not* be indented
media_folder: "public/media" # Media files will be stored in the repo under static/images/uploads
public_folder: "/media" # The src attribute for uploaded media will begin with /images/uploads


